# Scheduled CoffeeRewardsJob at every end of month at 23:50
coffee_rewards_job:
  cron: "50 23 30 * *"
  class: "CoffeeRewardsJob"
  queue: default

# Scheduled MovieRewardsJob at every day at 23:50
  cron: "50 23 * * *"
  class: "MovieRewardsJob"
  queue: default

# Scheduled CashRebatesJob at every day at 23:50
cash_rebates_job:
  cron: "50 23 * * *"
  class: "CashRebatesJob"
  queue: default

# Scheduled BonusPointsJob at every 3 months
bonus_points_job:
  cron: "50 23 01 */3 *"
  class: "BonusPointsJob"
  queue: default

# Scheduled ExpiringLoyaltyPointsJob at every year
expiring_loyalty_points_job:
  cron: "50 23 30 12 *"
  class: "ExpiringLoyaltyPointsJob"
  queue: default
